PERF_API_URL: "http://localhost/v2/api/cicd/"
api_params: 
 sla: 
  pageLoadTime: 2000
 baseline: 
  days: 7
  perc: 75
  padding: 1.2
 flags: 
  assertBaseline: true
  debug: false
  esTrace: false
  esCreate: false
  passOnFailedAssert: false
 log: 
  test_info: "Demo test_info"
  env_tester: "Demo tester"
  browser: "Demo browser"
  env_target: "Demo target"
  team: "DEMO TEAM"